version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports: -"5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=eidoox
      - RABBITMQ_DEFAULT_PASS=eidoox99
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
